name: flutter_zxing_example
description: Demonstrates how to use the flutter_zxing plugin.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_zxing:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
