name: flutter_zxing
description: A barcode scanner and generator natively in Flutter with Dart FFI based on ZXing.
version: 1.8.2
repository: https://github.com/khoren93/flutter_zxing

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  camera: ">=0.9.7 <0.12.0"
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  image: ^4.0.0
  image_picker: ^1.0.0

dev_dependencies:
  ffigen: ">=12.0.0 <17.0.0" # dart run ffigen --config ffigen.yaml
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  melos: ">=5.0.0 <7.0.0"

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

# Publish to pub.dev
# flutter pub publish --dry-run
# flutter pub publish

# Update zxing-cpp submodule
# git submodule update --remote
