name: flutter_zxing
description: A barcode scanner and generator natively in Flutter with Dart FFI based on ZXing.
version: 0.8.1
repository: https://github.com/khoren93/flutter_zxing

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  camera: ">=0.9.7 <0.11.0"
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  image: ^3.2.0

dev_dependencies:
  ffigen: ^6.0.0 # dart run ffigen
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.markosyan.flutter_zxing
        pluginClass: FlutterZxingPlugin
      ios:
        pluginClass: FlutterZxingPlugin

ffigen:
  name: GeneratedBindings
  description: Bindings to `native_verokit.h`.
  output: "lib/generated_bindings.dart"
  headers:
    entry-points:
      - "ios/Classes/src/native_zxing.h"
  functions:
    exclude:
      - 'resultToCodeResult'


# flutter pub publish --dry-run