name: zxscanner
description: A barcode scanner application.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_mobx: ^2.0.5
  flutter_zxing:
    path: ../
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  image: ^3.2.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  mobx: ^2.0.7
  path_provider: ^2.0.11
  share_plus: ^4.0.7
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.2 # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  hive_generator:
  icons_launcher: ^1.1.9 # flutter pub run icons_launcher:create
  mobx_codegen:


flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#131d25"
  image: assets/images/app_logo.png
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: true
  ios: true
  macos: false
  windows: false
  web: false
  remove_alpha_ios: true
  image_path: "assets/images/app_icon_border.png"
  image_path_ios: 'assets/images/app_icon.png'
  adaptive_icon_background: '#4C9BBA'
  adaptive_icon_foreground: 'assets/images/app_icon_adaptive.png'
  adaptive_icon_round: 'assets/images/app_icon_round.png'