name: zxscanner
description: A barcode scanner application.
publish_to: "none"

version: 1.2.0+14

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.0
  flutter_mobx: ^2.2.0
  flutter_zxing:
    path: ../
  font_awesome_flutter: ^10.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: any
  image_picker: ^1.0.0
  intl: ^0.19.0
  mobx: ^2.0.0
  path_provider: ^2.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.2.0

flutter_intl:
  main_locale: en_US
  enabled: true

dev_dependencies:
  build_runner: ^2.4.0
  # espresso: ^0.2.0+2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16 # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  hive_generator:
  icons_launcher: ^3.0.0 # flutter pub run icons_launcher:create
  # integration_test:
  #   sdk: flutter
  mobx_codegen: any

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#131d25"
  image: assets/images/app_logo.png
  info_plist_files:
    - "ios/Runner/Info-Debug.plist"
    - "ios/Runner/Info-Release.plist"

icons_launcher:
  image_path: "assets/images/app_icon_border.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/app_icon_border.png"
      adaptive_background_color: '#4C9BBA'
      adaptive_foreground_image: "assets/images/app_icon_foreground.png"
      adaptive_round_image: "assets/images/app_icon_round.png"
    ios:
      enable: true
      image_path: "assets/images/app_icon.png"
    web:
      enable: true
      image_path: "assets/images/app_icon_border.png"
      favicon_path: "assets/images/app_icon_round.png"
    macos:
      enable: false
      image_path: "assets/images/app_icon_border.png"
    windows:
      enable: false
      image_path: "assets/images/app_icon_border.png"
    linux:
      enable: false
      image_path: "assets/images/app_icon_border.png"